// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZE_PROJECT_HEADER_EXOTICA_PENDULUM_DYNAMICS_SOLVER_H_$
#define INITIALIZE_PROJECT_HEADER_EXOTICA_PENDULUM_DYNAMICS_SOLVER_H_$

#include <exotica_core/property.h>
#include <exotica_pendulum_dynamics_solver/pendulum_dynamics_solver_initializer.h>


namespace exotica
{

inline std::vector<Initializer> GetExoticaPendulumDynamicsSolverInitializers()
{
    std::vector<Initializer> ret;
    ret.push_back(PendulumDynamicsSolverInitializer().GetTemplate());
   return ret;
}

}

#endif
