// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZE_PROJECT_HEADER_EXOTICA_AICO_SOLVER_H_$
#define INITIALIZE_PROJECT_HEADER_EXOTICA_AICO_SOLVER_H_$

#include <exotica_core/property.h>
#include <exotica_aico_solver/approximate_inference_solver_initializer.h>
#include <exotica_aico_solver/aico_solver_initializer.h>
#include <exotica_aico_solver/bayesian_ik_solver_initializer.h>


namespace exotica
{

inline std::vector<Initializer> GetExoticaAicoSolverInitializers()
{
    std::vector<Initializer> ret;
    ret.push_back(ApproximateInferenceSolverInitializer().GetTemplate());
    ret.push_back(AICOSolverInitializer().GetTemplate());
    ret.push_back(BayesianIKSolverInitializer().GetTemplate());
   return ret;
}

}

#endif
