// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZE_PROJECT_HEADER_EXOTICA_PINOCCHIO_DYNAMICS_SOLVER_H_$
#define INITIALIZE_PROJECT_HEADER_EXOTICA_PINOCCHIO_DYNAMICS_SOLVER_H_$

#include <exotica_core/property.h>
#include <exotica_pinocchio_dynamics_solver/pinocchio_dynamics_solver_initializer.h>


namespace exotica
{

inline std::vector<Initializer> GetExoticaPinocchioDynamicsSolverInitializers()
{
    std::vector<Initializer> ret;
    ret.push_back(PinocchioDynamicsSolverInitializer().GetTemplate());
   return ret;
}

}

#endif
