// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZE_PROJECT_HEADER_EXOTICA_CARTPOLE_DYNAMICS_SOLVER_H_$
#define INITIALIZE_PROJECT_HEADER_EXOTICA_CARTPOLE_DYNAMICS_SOLVER_H_$

#include <exotica_core/property.h>
#include <exotica_cartpole_dynamics_solver/cartpole_dynamics_solver_initializer.h>


namespace exotica
{

inline std::vector<Initializer> GetExoticaCartpoleDynamicsSolverInitializers()
{
    std::vector<Initializer> ret;
    ret.push_back(CartpoleDynamicsSolverInitializer().GetTemplate());
   return ret;
}

}

#endif
