// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZE_PROJECT_HEADER_EXOTICA_ILQR_SOLVER_H_$
#define INITIALIZE_PROJECT_HEADER_EXOTICA_ILQR_SOLVER_H_$

#include <exotica_core/property.h>
#include <exotica_ilqr_solver/ilqr_solver_initializer.h>


namespace exotica
{

inline std::vector<Initializer> GetExoticaIlqrSolverInitializers()
{
    std::vector<Initializer> ret;
    ret.push_back(ILQRSolverInitializer().GetTemplate());
   return ret;
}

}

#endif
