// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZE_PROJECT_HEADER_EXOTICA_DDP_SOLVER_H_$
#define INITIALIZE_PROJECT_HEADER_EXOTICA_DDP_SOLVER_H_$

#include <exotica_core/property.h>
#include <exotica_ddp_solver/abstract_ddp_solver_initializer.h>
#include <exotica_ddp_solver/analytic_ddp_solver_initializer.h>
#include <exotica_ddp_solver/control_limited_ddp_solver_initializer.h>


namespace exotica
{

inline std::vector<Initializer> GetExoticaDdpSolverInitializers()
{
    std::vector<Initializer> ret;
    ret.push_back(AbstractDDPSolverInitializer().GetTemplate());
    ret.push_back(AnalyticDDPSolverInitializer().GetTemplate());
    ret.push_back(ControlLimitedDDPSolverInitializer().GetTemplate());
   return ret;
}

}

#endif
