// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZER_EXOTICA_CORE_TASK_MAPS_COLLISION_DISTANCE_INITIALIZER_H
#define INITIALIZER_EXOTICA_CORE_TASK_MAPS_COLLISION_DISTANCE_INITIALIZER_H

#include <exotica_core/property.h>

namespace exotica
{
inline std::vector<Initializer> GetExoticaCoreTaskMapsInitializers();
}

namespace exotica
{

class CollisionDistanceInitializer : public InitializerBase
{
public:
    static std::string GetContainerName() {return "exotica/CollisionDistance" ;}

    CollisionDistanceInitializer() : InitializerBase(),
        Debug( false) ,
        EndEffector( std::vector<exotica::Initializer>()) ,
        WorldMargin( 0.1) ,
        RobotMargin( 0.1) ,
        CheckSelfCollision( true) 
    {
    }

    CollisionDistanceInitializer( std::string _Name, bool _Debug =  false, std::vector<exotica::Initializer> _EndEffector =  std::vector<exotica::Initializer>(), double _WorldMargin =  0.1, double _RobotMargin =  0.1, bool _CheckSelfCollision =  true) : InitializerBase(),
        Name(_Name) ,
        Debug(_Debug) ,
        EndEffector(_EndEffector) ,
        WorldMargin(_WorldMargin) ,
        RobotMargin(_RobotMargin) ,
        CheckSelfCollision(_CheckSelfCollision) 
    {
    }

    CollisionDistanceInitializer(const Initializer& other) : CollisionDistanceInitializer()
    {
        if (other.HasProperty("Name")) {const Property& prop=other.properties_.at("Name"); if(prop.IsSet()) Name = boost::any_cast<std::string>(prop.Get());}
        if (other.HasProperty("Debug")) {const Property& prop=other.properties_.at("Debug"); if(prop.IsSet()) Debug = prop.IsStringType()?ParseBool(boost::any_cast<std::string>(prop.Get())):boost::any_cast<bool>(prop.Get());}
        if (other.HasProperty("EndEffector")) {const Property& prop=other.properties_.at("EndEffector"); if(prop.IsSet()) EndEffector = boost::any_cast<std::vector<exotica::Initializer>>(prop.Get());}
        if (other.HasProperty("WorldMargin")) {const Property& prop=other.properties_.at("WorldMargin"); if(prop.IsSet()) WorldMargin = prop.IsStringType()?ParseDouble(boost::any_cast<std::string>(prop.Get())):boost::any_cast<double>(prop.Get());}
        if (other.HasProperty("RobotMargin")) {const Property& prop=other.properties_.at("RobotMargin"); if(prop.IsSet()) RobotMargin = prop.IsStringType()?ParseDouble(boost::any_cast<std::string>(prop.Get())):boost::any_cast<double>(prop.Get());}
        if (other.HasProperty("CheckSelfCollision")) {const Property& prop=other.properties_.at("CheckSelfCollision"); if(prop.IsSet()) CheckSelfCollision = prop.IsStringType()?ParseBool(boost::any_cast<std::string>(prop.Get())):boost::any_cast<bool>(prop.Get());}
    }

    virtual Initializer GetTemplate() const
    {
        return (Initializer)CollisionDistanceInitializer();
    }

    virtual std::vector<Initializer> GetAllTemplates() const
    {
        return GetExoticaCoreTaskMapsInitializers();
    }

    virtual void Check(const Initializer& other) const
    {
        if(!other.HasProperty("Name") || !other.properties_.at("Name").IsSet()) ThrowPretty("Initializer CollisionDistanceInitializer requires property Name to be set!");
    }

    operator Initializer()
    {
        Initializer ret(GetContainerName());
        ret.properties_.emplace("Name", Property("Name", true, boost::any(Name)));
        ret.properties_.emplace("Debug", Property("Debug", false, boost::any(Debug)));
        ret.properties_.emplace("EndEffector", Property("EndEffector", false, boost::any(EndEffector)));
        ret.properties_.emplace("WorldMargin", Property("WorldMargin", false, boost::any(WorldMargin)));
        ret.properties_.emplace("RobotMargin", Property("RobotMargin", false, boost::any(RobotMargin)));
        ret.properties_.emplace("CheckSelfCollision", Property("CheckSelfCollision", false, boost::any(CheckSelfCollision)));
        return ret;
    }

    std::string Name;
    bool Debug;
    std::vector<exotica::Initializer> EndEffector;
    double WorldMargin;
    double RobotMargin;
    bool CheckSelfCollision;
};

}

#include<exotica_core_task_maps/exotica_core_task_maps_initializers_numerator.h>

#include <exotica_core/frame_initializer.h>

#endif