// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZER_EXOTICA_CORE_TASK_MAPS_FRAME_WITH_BOX_LIMITS_INITIALIZER_H
#define INITIALIZER_EXOTICA_CORE_TASK_MAPS_FRAME_WITH_BOX_LIMITS_INITIALIZER_H

#include <exotica_core/property.h>

namespace exotica
{
inline std::vector<Initializer> GetExoticaCoreTaskMapsInitializers();
}

namespace exotica
{

class FrameWithBoxLimitsInitializer : public InitializerBase
{
public:
    static std::string GetContainerName() {return "exotica/FrameWithBoxLimits" ;}

    FrameWithBoxLimitsInitializer() : InitializerBase(),
        LinkOffset( Eigen::IdentityTransform()) ,
        Base( "") ,
        BaseOffset( Eigen::IdentityTransform()) 
    {
    }

    FrameWithBoxLimitsInitializer( std::string _Link, Eigen::Vector2d _XLim, Eigen::Vector2d _YLim, Eigen::Vector2d _ZLim, Eigen::VectorXd _LinkOffset =  Eigen::IdentityTransform(), std::string _Base =  "", Eigen::VectorXd _BaseOffset =  Eigen::IdentityTransform()) : InitializerBase(),
        Link(_Link) ,
        XLim(_XLim) ,
        YLim(_YLim) ,
        ZLim(_ZLim) ,
        LinkOffset(_LinkOffset) ,
        Base(_Base) ,
        BaseOffset(_BaseOffset) 
    {
    }

    FrameWithBoxLimitsInitializer(const Initializer& other) : FrameWithBoxLimitsInitializer()
    {
        if (other.HasProperty("Link")) {const Property& prop=other.properties_.at("Link"); if(prop.IsSet()) Link = boost::any_cast<std::string>(prop.Get());}
        if (other.HasProperty("XLim")) {const Property& prop=other.properties_.at("XLim"); if(prop.IsSet()) XLim = prop.IsStringType()?ParseVector<double,2>(boost::any_cast<std::string>(prop.Get())):boost::any_cast<Eigen::Vector2d>(prop.Get());}
        if (other.HasProperty("YLim")) {const Property& prop=other.properties_.at("YLim"); if(prop.IsSet()) YLim = prop.IsStringType()?ParseVector<double,2>(boost::any_cast<std::string>(prop.Get())):boost::any_cast<Eigen::Vector2d>(prop.Get());}
        if (other.HasProperty("ZLim")) {const Property& prop=other.properties_.at("ZLim"); if(prop.IsSet()) ZLim = prop.IsStringType()?ParseVector<double,2>(boost::any_cast<std::string>(prop.Get())):boost::any_cast<Eigen::Vector2d>(prop.Get());}
        if (other.HasProperty("LinkOffset")) {const Property& prop=other.properties_.at("LinkOffset"); if(prop.IsSet()) LinkOffset = prop.IsStringType()?ParseVector<double,Eigen::Dynamic>(boost::any_cast<std::string>(prop.Get())):boost::any_cast<Eigen::VectorXd>(prop.Get());}
        if (other.HasProperty("Base")) {const Property& prop=other.properties_.at("Base"); if(prop.IsSet()) Base = boost::any_cast<std::string>(prop.Get());}
        if (other.HasProperty("BaseOffset")) {const Property& prop=other.properties_.at("BaseOffset"); if(prop.IsSet()) BaseOffset = prop.IsStringType()?ParseVector<double,Eigen::Dynamic>(boost::any_cast<std::string>(prop.Get())):boost::any_cast<Eigen::VectorXd>(prop.Get());}
    }

    virtual Initializer GetTemplate() const
    {
        return (Initializer)FrameWithBoxLimitsInitializer();
    }

    virtual std::vector<Initializer> GetAllTemplates() const
    {
        return GetExoticaCoreTaskMapsInitializers();
    }

    virtual void Check(const Initializer& other) const
    {
        if(!other.HasProperty("Link") || !other.properties_.at("Link").IsSet()) ThrowPretty("Initializer FrameWithBoxLimitsInitializer requires property Link to be set!");
        if(!other.HasProperty("XLim") || !other.properties_.at("XLim").IsSet()) ThrowPretty("Initializer FrameWithBoxLimitsInitializer requires property XLim to be set!");
        if(!other.HasProperty("YLim") || !other.properties_.at("YLim").IsSet()) ThrowPretty("Initializer FrameWithBoxLimitsInitializer requires property YLim to be set!");
        if(!other.HasProperty("ZLim") || !other.properties_.at("ZLim").IsSet()) ThrowPretty("Initializer FrameWithBoxLimitsInitializer requires property ZLim to be set!");
    }

    operator Initializer()
    {
        Initializer ret(GetContainerName());
        ret.properties_.emplace("Link", Property("Link", true, boost::any(Link)));
        ret.properties_.emplace("XLim", Property("XLim", true, boost::any(XLim)));
        ret.properties_.emplace("YLim", Property("YLim", true, boost::any(YLim)));
        ret.properties_.emplace("ZLim", Property("ZLim", true, boost::any(ZLim)));
        ret.properties_.emplace("LinkOffset", Property("LinkOffset", false, boost::any(LinkOffset)));
        ret.properties_.emplace("Base", Property("Base", false, boost::any(Base)));
        ret.properties_.emplace("BaseOffset", Property("BaseOffset", false, boost::any(BaseOffset)));
        return ret;
    }

    std::string Link;
    Eigen::Vector2d XLim;
    Eigen::Vector2d YLim;
    Eigen::Vector2d ZLim;
    Eigen::VectorXd LinkOffset;
    std::string Base;
    Eigen::VectorXd BaseOffset;
};

}

#include<exotica_core_task_maps/exotica_core_task_maps_initializers_numerator.h>


#endif