// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZER_EXOTICA_CORE_TASK_MAPS_POINT_TO_LINE_INITIALIZER_H
#define INITIALIZER_EXOTICA_CORE_TASK_MAPS_POINT_TO_LINE_INITIALIZER_H

#include <exotica_core/property.h>

namespace exotica
{
inline std::vector<Initializer> GetExoticaCoreTaskMapsInitializers();
}

namespace exotica
{

class PointToLineInitializer : public InitializerBase
{
public:
    static std::string GetContainerName() {return "exotica/PointToLine" ;}

    PointToLineInitializer() : InitializerBase(),
        Debug( false) ,
        EndEffector( std::vector<exotica::Initializer>()) ,
        Infinite( true) ,
        Visualise( false) 
    {
    }

    PointToLineInitializer( std::string _Name, Eigen::Vector3d _EndPoint, bool _Debug =  false, std::vector<exotica::Initializer> _EndEffector =  std::vector<exotica::Initializer>(), bool _Infinite =  true, bool _Visualise =  false) : InitializerBase(),
        Name(_Name) ,
        EndPoint(_EndPoint) ,
        Debug(_Debug) ,
        EndEffector(_EndEffector) ,
        Infinite(_Infinite) ,
        Visualise(_Visualise) 
    {
    }

    PointToLineInitializer(const Initializer& other) : PointToLineInitializer()
    {
        if (other.HasProperty("Name")) {const Property& prop=other.properties_.at("Name"); if(prop.IsSet()) Name = boost::any_cast<std::string>(prop.Get());}
        if (other.HasProperty("EndPoint")) {const Property& prop=other.properties_.at("EndPoint"); if(prop.IsSet()) EndPoint = prop.IsStringType()?ParseVector<double,3>(boost::any_cast<std::string>(prop.Get())):boost::any_cast<Eigen::Vector3d>(prop.Get());}
        if (other.HasProperty("Debug")) {const Property& prop=other.properties_.at("Debug"); if(prop.IsSet()) Debug = prop.IsStringType()?ParseBool(boost::any_cast<std::string>(prop.Get())):boost::any_cast<bool>(prop.Get());}
        if (other.HasProperty("EndEffector")) {const Property& prop=other.properties_.at("EndEffector"); if(prop.IsSet()) EndEffector = boost::any_cast<std::vector<exotica::Initializer>>(prop.Get());}
        if (other.HasProperty("Infinite")) {const Property& prop=other.properties_.at("Infinite"); if(prop.IsSet()) Infinite = prop.IsStringType()?ParseBool(boost::any_cast<std::string>(prop.Get())):boost::any_cast<bool>(prop.Get());}
        if (other.HasProperty("Visualise")) {const Property& prop=other.properties_.at("Visualise"); if(prop.IsSet()) Visualise = prop.IsStringType()?ParseBool(boost::any_cast<std::string>(prop.Get())):boost::any_cast<bool>(prop.Get());}
    }

    virtual Initializer GetTemplate() const
    {
        return (Initializer)PointToLineInitializer();
    }

    virtual std::vector<Initializer> GetAllTemplates() const
    {
        return GetExoticaCoreTaskMapsInitializers();
    }

    virtual void Check(const Initializer& other) const
    {
        if(!other.HasProperty("Name") || !other.properties_.at("Name").IsSet()) ThrowPretty("Initializer PointToLineInitializer requires property Name to be set!");
        if(!other.HasProperty("EndPoint") || !other.properties_.at("EndPoint").IsSet()) ThrowPretty("Initializer PointToLineInitializer requires property EndPoint to be set!");
    }

    operator Initializer()
    {
        Initializer ret(GetContainerName());
        ret.properties_.emplace("Name", Property("Name", true, boost::any(Name)));
        ret.properties_.emplace("EndPoint", Property("EndPoint", true, boost::any(EndPoint)));
        ret.properties_.emplace("Debug", Property("Debug", false, boost::any(Debug)));
        ret.properties_.emplace("EndEffector", Property("EndEffector", false, boost::any(EndEffector)));
        ret.properties_.emplace("Infinite", Property("Infinite", false, boost::any(Infinite)));
        ret.properties_.emplace("Visualise", Property("Visualise", false, boost::any(Visualise)));
        return ret;
    }

    std::string Name;
    Eigen::Vector3d EndPoint;
    bool Debug;
    std::vector<exotica::Initializer> EndEffector;
    bool Infinite;
    bool Visualise;
};

}

#include<exotica_core_task_maps/exotica_core_task_maps_initializers_numerator.h>

#include <exotica_core/frame_initializer.h>

#endif