// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZE_PROJECT_HEADER_EXOTICA_TIME_INDEXED_RRT_CONNECT_SOLVER_H_$
#define INITIALIZE_PROJECT_HEADER_EXOTICA_TIME_INDEXED_RRT_CONNECT_SOLVER_H_$

#include <exotica_core/property.h>
#include <exotica_time_indexed_rrt_connect_solver/time_indexed_rrt_connect_initializer.h>


namespace exotica
{

inline std::vector<Initializer> GetExoticaTimeIndexedRrtConnectSolverInitializers()
{
    std::vector<Initializer> ret;
    ret.push_back(TimeIndexedRRTConnectSolverInitializer().GetTemplate());
   return ret;
}

}

#endif
