// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZE_PROJECT_HEADER_EXOTICA_IK_SOLVER_H_$
#define INITIALIZE_PROJECT_HEADER_EXOTICA_IK_SOLVER_H_$

#include <exotica_core/property.h>
#include <exotica_ik_solver/ik_solver_initializer.h>


namespace exotica
{

inline std::vector<Initializer> GetExoticaIkSolverInitializers()
{
    std::vector<Initializer> ret;
    ret.push_back(IKSolverInitializer().GetTemplate());
   return ret;
}

}

#endif
