// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZE_PROJECT_HEADER_EXOTICA_DOUBLE_INTEGRATOR_DYNAMICS_SOLVER_H_$
#define INITIALIZE_PROJECT_HEADER_EXOTICA_DOUBLE_INTEGRATOR_DYNAMICS_SOLVER_H_$

#include <exotica_core/property.h>
#include <exotica_double_integrator_dynamics_solver/double_integrator_dynamics_solver_initializer.h>


namespace exotica
{

inline std::vector<Initializer> GetExoticaDoubleIntegratorDynamicsSolverInitializers()
{
    std::vector<Initializer> ret;
    ret.push_back(DoubleIntegratorDynamicsSolverInitializer().GetTemplate());
   return ret;
}

}

#endif
