// This file was automatically generated. Do not edit this file!
#ifndef INITIALIZER_EXOTICA_CORE_OBJECT_INITIALIZER_H
#define INITIALIZER_EXOTICA_CORE_OBJECT_INITIALIZER_H

#include <exotica_core/property.h>

namespace exotica
{
inline std::vector<Initializer> GetExoticaCoreInitializers();
}

namespace exotica
{

class ObjectInitializer : public InitializerBase
{
public:
    static std::string GetContainerName() {return "exotica/Object" ;}

    ObjectInitializer() : InitializerBase(),
        Debug( false) 
    {
    }

    ObjectInitializer( std::string _Name, bool _Debug =  false) : InitializerBase(),
        Name(_Name) ,
        Debug(_Debug) 
    {
    }

    ObjectInitializer(const Initializer& other) : ObjectInitializer()
    {
        if (other.HasProperty("Name")) {const Property& prop=other.properties_.at("Name"); if(prop.IsSet()) Name = boost::any_cast<std::string>(prop.Get());}
        if (other.HasProperty("Debug")) {const Property& prop=other.properties_.at("Debug"); if(prop.IsSet()) Debug = prop.IsStringType()?ParseBool(boost::any_cast<std::string>(prop.Get())):boost::any_cast<bool>(prop.Get());}
    }

    virtual Initializer GetTemplate() const
    {
        return (Initializer)ObjectInitializer();
    }

    virtual std::vector<Initializer> GetAllTemplates() const
    {
        return GetExoticaCoreInitializers();
    }

    virtual void Check(const Initializer& other) const
    {
        if(!other.HasProperty("Name") || !other.properties_.at("Name").IsSet()) ThrowPretty("Initializer ObjectInitializer requires property Name to be set!");
    }

    operator Initializer()
    {
        Initializer ret(GetContainerName());
        ret.properties_.emplace("Name", Property("Name", true, boost::any(Name)));
        ret.properties_.emplace("Debug", Property("Debug", false, boost::any(Debug)));
        return ret;
    }

    std::string Name;
    bool Debug;
};

}

#include<exotica_core/exotica_core_initializers_numerator.h>


#endif